// @flow

import { expectSaga } from 'redux-saga-test-plan';
import * as matchers from 'redux-saga-test-plan/matchers';
import { dynamic } from 'redux-saga-test-plan/providers';

import asyncRequests from 'modules/asyncRequests';
import topics from 'modules/topics';

import actions from '../../actions';

import { sagas } from '..';

describe(`forkTopic`, (): void => {

  let dummyUserId: string;
  let dummyTopicId: string;
  let dummyForkedTopicId: string;

  beforeEach((): void => {
    dummyUserId = 'dummyUserId';
    dummyTopicId = 'dummyTopicId';
    dummyForkedTopicId = 'dummyForkedTopicId';
  });

  it(`puts a topics FORK action containing the passed topicId, then puts a users ADD_TOPIC_ID action containing the id generated by the api`, (): void => {
    const dummyAction = actions.forkTopic(dummyUserId, dummyTopicId);

    return expectSaga(sagas.forkTopic, dummyAction)
      .provide([
        [matchers.call.fn(asyncRequests.lib.putAndReturn), dynamic(({ args: [action] }: any, next: any): any => {
          return (action.type === topics.actionTypes.FORK) ? { id: dummyForkedTopicId } : next();
        })],
      ])
      .call(asyncRequests.lib.putAndReturn, topics.actions.fork(dummyTopicId))
      .put(actions.addTopicId(dummyUserId, dummyForkedTopicId))
      .run();
  });

});
