// flow-typed signature: d8dec39f1feb80f31a8b160d3fa3fd42
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^5.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/postProcessPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/preProcessPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/processPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/utils/isObject' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/utils/normalize' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/utils/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/cjs'>;
}
declare module 'copy-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/index'>;
}
declare module 'copy-webpack-plugin/dist/postProcessPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/postProcessPattern'>;
}
declare module 'copy-webpack-plugin/dist/preProcessPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/preProcessPattern'>;
}
declare module 'copy-webpack-plugin/dist/processPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/processPattern'>;
}
declare module 'copy-webpack-plugin/dist/utils/isObject.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/utils/isObject'>;
}
declare module 'copy-webpack-plugin/dist/utils/normalize.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/utils/normalize'>;
}
declare module 'copy-webpack-plugin/dist/utils/promisify.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/utils/promisify'>;
}
