// flow-typed signature: fa118e9a0c2519fdf78c6a9b359ff47d
// flow-typed version: <<STUB>>/jest-date-mock_v^1.0.7/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-date-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-date-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-date-mock/lib/date' {
  declare module.exports: any;
}

declare module 'jest-date-mock/lib/index' {
  declare module.exports: any;
}

declare module 'jest-date-mock/lib/mockDate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-date-mock/lib/date.js' {
  declare module.exports: $Exports<'jest-date-mock/lib/date'>;
}
declare module 'jest-date-mock/lib/index.js' {
  declare module.exports: $Exports<'jest-date-mock/lib/index'>;
}
declare module 'jest-date-mock/lib/mockDate.js' {
  declare module.exports: $Exports<'jest-date-mock/lib/mockDate'>;
}
