// flow-typed signature: 9dd80645841914b33cef97df17dc142d
// flow-typed version: <<STUB>>/jest-dev-server_v^3.7.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-dev-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-dev-server/lib/global' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-dev-server/index' {
  declare module.exports: $Exports<'jest-dev-server'>;
}
declare module 'jest-dev-server/index.js' {
  declare module.exports: $Exports<'jest-dev-server'>;
}
declare module 'jest-dev-server/lib/global.js' {
  declare module.exports: $Exports<'jest-dev-server/lib/global'>;
}
