// flow-typed signature: ce5dad8b7f470b5d6408c506e0c096db
// flow-typed version: <<STUB>>/pundit_v^0.0.2/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pundit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pundit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pundit/dist/index' {
  declare module.exports: any;
}

declare module 'pundit/dist/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pundit/dist/index.js' {
  declare module.exports: $Exports<'pundit/dist/index'>;
}
declare module 'pundit/dist/react.js' {
  declare module.exports: $Exports<'pundit/dist/react'>;
}
