// flow-typed signature: 78284bc7bcd6b28cb4bb0ba596d719ca
// flow-typed version: <<STUB>>/react-dnd-test-utils_v^7.4.4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-test-utils/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'react-dnd-test-utils/lib/cjs/utils' {
  declare module.exports: any;
}

declare module 'react-dnd-test-utils/lib/esm/index' {
  declare module.exports: any;
}

declare module 'react-dnd-test-utils/lib/esm/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-test-utils/lib/cjs/index.js' {
  declare module.exports: $Exports<'react-dnd-test-utils/lib/cjs/index'>;
}
declare module 'react-dnd-test-utils/lib/cjs/utils.js' {
  declare module.exports: $Exports<'react-dnd-test-utils/lib/cjs/utils'>;
}
declare module 'react-dnd-test-utils/lib/esm/index.js' {
  declare module.exports: $Exports<'react-dnd-test-utils/lib/esm/index'>;
}
declare module 'react-dnd-test-utils/lib/esm/utils.js' {
  declare module.exports: $Exports<'react-dnd-test-utils/lib/esm/utils'>;
}
