// flow-typed signature: e7541e67c5d3c7e3ec7ebd6cb7725e2b
// flow-typed version: <<STUB>>/react-dnd-html5-backend_v^7.4.4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-html5-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-html5-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.min' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/BrowserDetector' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/EnterLeaveCounter' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/getEmptyImage' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/HTML5Backend' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/MonotonicInterpolant' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/getDataFromDataTransfer' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/index' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/NativeDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/nativeTypesConfig' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/NativeTypes' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/OffsetUtils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/cjs/utils/discount_lodash' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/BrowserDetector' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/EnterLeaveCounter' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/getEmptyImage' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/HTML5Backend' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/index' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/MonotonicInterpolant' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/getDataFromDataTransfer' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/index' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/NativeDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/nativeTypesConfig' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/NativeTypes' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/OffsetUtils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/esm/utils/discount_lodash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/ReactDnDHTML5Backend'>;
}
declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.min.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.min'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/BrowserDetector.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/BrowserDetector'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/EnterLeaveCounter.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/EnterLeaveCounter'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/getEmptyImage.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/getEmptyImage'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/HTML5Backend.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/HTML5Backend'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/index'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/interfaces.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/interfaces'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/MonotonicInterpolant.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/MonotonicInterpolant'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/getDataFromDataTransfer.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/NativeDragSources/getDataFromDataTransfer'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/NativeDragSources/index'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/NativeDragSource.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/NativeDragSources/NativeDragSource'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/NativeDragSources/nativeTypesConfig.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/NativeDragSources/nativeTypesConfig'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/NativeTypes.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/NativeTypes'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/OffsetUtils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/OffsetUtils'>;
}
declare module 'react-dnd-html5-backend/lib/cjs/utils/discount_lodash.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/cjs/utils/discount_lodash'>;
}
declare module 'react-dnd-html5-backend/lib/esm/BrowserDetector.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/BrowserDetector'>;
}
declare module 'react-dnd-html5-backend/lib/esm/EnterLeaveCounter.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/EnterLeaveCounter'>;
}
declare module 'react-dnd-html5-backend/lib/esm/getEmptyImage.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/getEmptyImage'>;
}
declare module 'react-dnd-html5-backend/lib/esm/HTML5Backend.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/HTML5Backend'>;
}
declare module 'react-dnd-html5-backend/lib/esm/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/index'>;
}
declare module 'react-dnd-html5-backend/lib/esm/interfaces.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/interfaces'>;
}
declare module 'react-dnd-html5-backend/lib/esm/MonotonicInterpolant.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/MonotonicInterpolant'>;
}
declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/getDataFromDataTransfer.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/NativeDragSources/getDataFromDataTransfer'>;
}
declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/NativeDragSources/index'>;
}
declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/NativeDragSource.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/NativeDragSources/NativeDragSource'>;
}
declare module 'react-dnd-html5-backend/lib/esm/NativeDragSources/nativeTypesConfig.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/NativeDragSources/nativeTypesConfig'>;
}
declare module 'react-dnd-html5-backend/lib/esm/NativeTypes.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/NativeTypes'>;
}
declare module 'react-dnd-html5-backend/lib/esm/OffsetUtils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/OffsetUtils'>;
}
declare module 'react-dnd-html5-backend/lib/esm/utils/discount_lodash.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/esm/utils/discount_lodash'>;
}
