// flow-typed signature: 67dd99edaf9e90964b49f49cf46f06e8
// flow-typed version: <<STUB>>/react-dnd_v^7.4.5/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd/dist/ReactDnD' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/ReactDnD.min' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/DragDropContext' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/internal/drag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/internal/drop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/internal/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/internal/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/internal/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/interfaces/classApi' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/interfaces/hooksApi' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/interfaces/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/interfaces/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/interfaces/options' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/registerSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/registerTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/checkDecoratorArguments' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/cloneWithRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/discount_lodash' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/disposables/CompositeDisposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/disposables/Disposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/disposables/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/disposables/SerialDisposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/getDecoratedComponent' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/isRefable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/isValidType' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/utils/polyfills/endsWith' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/cjs/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/DragDropContext' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/internal/drag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/internal/drop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/internal/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/internal/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/internal/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/interfaces/classApi' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/interfaces/hooksApi' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/interfaces/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/interfaces/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/interfaces/options' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/registerSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/registerTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/checkDecoratorArguments' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/cloneWithRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/discount_lodash' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/disposables/CompositeDisposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/disposables/Disposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/disposables/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/disposables/SerialDisposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/getDecoratedComponent' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/isRefable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/isValidType' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/utils/polyfills/endsWith' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/esm/wrapConnectorHooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd/dist/ReactDnD.js' {
  declare module.exports: $Exports<'react-dnd/dist/ReactDnD'>;
}
declare module 'react-dnd/dist/ReactDnD.min.js' {
  declare module.exports: $Exports<'react-dnd/dist/ReactDnD.min'>;
}
declare module 'react-dnd/lib/cjs/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/createSourceFactory'>;
}
declare module 'react-dnd/lib/cjs/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/createTargetFactory'>;
}
declare module 'react-dnd/lib/cjs/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/decorateHandler'>;
}
declare module 'react-dnd/lib/cjs/DragDropContext.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/DragDropContext'>;
}
declare module 'react-dnd/lib/cjs/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/DragLayer'>;
}
declare module 'react-dnd/lib/cjs/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/DragPreviewImage'>;
}
declare module 'react-dnd/lib/cjs/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/DragSource'>;
}
declare module 'react-dnd/lib/cjs/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/lib/cjs/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/DropTarget'>;
}
declare module 'react-dnd/lib/cjs/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/lib/cjs/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/index'>;
}
declare module 'react-dnd/lib/cjs/hooks/internal/drag.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/internal/drag'>;
}
declare module 'react-dnd/lib/cjs/hooks/internal/drop.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/internal/drop'>;
}
declare module 'react-dnd/lib/cjs/hooks/internal/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/internal/useCollector'>;
}
declare module 'react-dnd/lib/cjs/hooks/internal/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/internal/useDragDropManager'>;
}
declare module 'react-dnd/lib/cjs/hooks/internal/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/internal/useMonitorOutput'>;
}
declare module 'react-dnd/lib/cjs/hooks/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/useDrag'>;
}
declare module 'react-dnd/lib/cjs/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/useDragLayer'>;
}
declare module 'react-dnd/lib/cjs/hooks/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/hooks/useDrop'>;
}
declare module 'react-dnd/lib/cjs/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/index'>;
}
declare module 'react-dnd/lib/cjs/interfaces/classApi.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/interfaces/classApi'>;
}
declare module 'react-dnd/lib/cjs/interfaces/hooksApi.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/interfaces/hooksApi'>;
}
declare module 'react-dnd/lib/cjs/interfaces/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/interfaces/index'>;
}
declare module 'react-dnd/lib/cjs/interfaces/monitors.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/interfaces/monitors'>;
}
declare module 'react-dnd/lib/cjs/interfaces/options.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/interfaces/options'>;
}
declare module 'react-dnd/lib/cjs/registerSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/registerSource'>;
}
declare module 'react-dnd/lib/cjs/registerTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/registerTarget'>;
}
declare module 'react-dnd/lib/cjs/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/SourceConnector'>;
}
declare module 'react-dnd/lib/cjs/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/TargetConnector'>;
}
declare module 'react-dnd/lib/cjs/utils/checkDecoratorArguments.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/checkDecoratorArguments'>;
}
declare module 'react-dnd/lib/cjs/utils/cloneWithRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/cloneWithRef'>;
}
declare module 'react-dnd/lib/cjs/utils/discount_lodash.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/discount_lodash'>;
}
declare module 'react-dnd/lib/cjs/utils/disposables/CompositeDisposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/disposables/CompositeDisposable'>;
}
declare module 'react-dnd/lib/cjs/utils/disposables/Disposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/disposables/Disposable'>;
}
declare module 'react-dnd/lib/cjs/utils/disposables/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/disposables/index'>;
}
declare module 'react-dnd/lib/cjs/utils/disposables/SerialDisposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/disposables/SerialDisposable'>;
}
declare module 'react-dnd/lib/cjs/utils/getDecoratedComponent.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/getDecoratedComponent'>;
}
declare module 'react-dnd/lib/cjs/utils/isRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/isRef'>;
}
declare module 'react-dnd/lib/cjs/utils/isRefable.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/isRefable'>;
}
declare module 'react-dnd/lib/cjs/utils/isValidType.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/isValidType'>;
}
declare module 'react-dnd/lib/cjs/utils/polyfills/endsWith.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/utils/polyfills/endsWith'>;
}
declare module 'react-dnd/lib/cjs/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/lib/cjs/wrapConnectorHooks'>;
}
declare module 'react-dnd/lib/esm/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/createSourceFactory'>;
}
declare module 'react-dnd/lib/esm/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/createTargetFactory'>;
}
declare module 'react-dnd/lib/esm/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/decorateHandler'>;
}
declare module 'react-dnd/lib/esm/DragDropContext.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/DragDropContext'>;
}
declare module 'react-dnd/lib/esm/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/DragLayer'>;
}
declare module 'react-dnd/lib/esm/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/DragPreviewImage'>;
}
declare module 'react-dnd/lib/esm/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/DragSource'>;
}
declare module 'react-dnd/lib/esm/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/lib/esm/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/DropTarget'>;
}
declare module 'react-dnd/lib/esm/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/lib/esm/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/index'>;
}
declare module 'react-dnd/lib/esm/hooks/internal/drag.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/internal/drag'>;
}
declare module 'react-dnd/lib/esm/hooks/internal/drop.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/internal/drop'>;
}
declare module 'react-dnd/lib/esm/hooks/internal/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/internal/useCollector'>;
}
declare module 'react-dnd/lib/esm/hooks/internal/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/internal/useDragDropManager'>;
}
declare module 'react-dnd/lib/esm/hooks/internal/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/internal/useMonitorOutput'>;
}
declare module 'react-dnd/lib/esm/hooks/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/useDrag'>;
}
declare module 'react-dnd/lib/esm/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/useDragLayer'>;
}
declare module 'react-dnd/lib/esm/hooks/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/hooks/useDrop'>;
}
declare module 'react-dnd/lib/esm/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/index'>;
}
declare module 'react-dnd/lib/esm/interfaces/classApi.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/interfaces/classApi'>;
}
declare module 'react-dnd/lib/esm/interfaces/hooksApi.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/interfaces/hooksApi'>;
}
declare module 'react-dnd/lib/esm/interfaces/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/interfaces/index'>;
}
declare module 'react-dnd/lib/esm/interfaces/monitors.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/interfaces/monitors'>;
}
declare module 'react-dnd/lib/esm/interfaces/options.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/interfaces/options'>;
}
declare module 'react-dnd/lib/esm/registerSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/registerSource'>;
}
declare module 'react-dnd/lib/esm/registerTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/registerTarget'>;
}
declare module 'react-dnd/lib/esm/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/SourceConnector'>;
}
declare module 'react-dnd/lib/esm/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/TargetConnector'>;
}
declare module 'react-dnd/lib/esm/utils/checkDecoratorArguments.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/checkDecoratorArguments'>;
}
declare module 'react-dnd/lib/esm/utils/cloneWithRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/cloneWithRef'>;
}
declare module 'react-dnd/lib/esm/utils/discount_lodash.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/discount_lodash'>;
}
declare module 'react-dnd/lib/esm/utils/disposables/CompositeDisposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/disposables/CompositeDisposable'>;
}
declare module 'react-dnd/lib/esm/utils/disposables/Disposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/disposables/Disposable'>;
}
declare module 'react-dnd/lib/esm/utils/disposables/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/disposables/index'>;
}
declare module 'react-dnd/lib/esm/utils/disposables/SerialDisposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/disposables/SerialDisposable'>;
}
declare module 'react-dnd/lib/esm/utils/getDecoratedComponent.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/getDecoratedComponent'>;
}
declare module 'react-dnd/lib/esm/utils/isRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/isRef'>;
}
declare module 'react-dnd/lib/esm/utils/isRefable.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/isRefable'>;
}
declare module 'react-dnd/lib/esm/utils/isValidType.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/isValidType'>;
}
declare module 'react-dnd/lib/esm/utils/polyfills/endsWith.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/utils/polyfills/endsWith'>;
}
declare module 'react-dnd/lib/esm/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/lib/esm/wrapConnectorHooks'>;
}
