// flow-typed signature: c5d6196c1ae7daddfe1381b011dac2c6
// flow-typed version: <<STUB>>/react-voice-components_v^1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-voice-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-voice-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-voice-components/lib/VoicePlayer' {
  declare module.exports: any;
}

declare module 'react-voice-components/lib/VoiceRecognition' {
  declare module.exports: any;
}

declare module 'react-voice-components/stories/index' {
  declare module.exports: any;
}

declare module 'react-voice-components/stories/VoicePlayerDemo' {
  declare module.exports: any;
}

declare module 'react-voice-components/stories/VoiceRecognitionDemo' {
  declare module.exports: any;
}

declare module 'react-voice-components/webpackfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-voice-components/index' {
  declare module.exports: $Exports<'react-voice-components'>;
}
declare module 'react-voice-components/index.js' {
  declare module.exports: $Exports<'react-voice-components'>;
}
declare module 'react-voice-components/lib/VoicePlayer.js' {
  declare module.exports: $Exports<'react-voice-components/lib/VoicePlayer'>;
}
declare module 'react-voice-components/lib/VoiceRecognition.js' {
  declare module.exports: $Exports<'react-voice-components/lib/VoiceRecognition'>;
}
declare module 'react-voice-components/stories/index.js' {
  declare module.exports: $Exports<'react-voice-components/stories/index'>;
}
declare module 'react-voice-components/stories/VoicePlayerDemo.js' {
  declare module.exports: $Exports<'react-voice-components/stories/VoicePlayerDemo'>;
}
declare module 'react-voice-components/stories/VoiceRecognitionDemo.js' {
  declare module.exports: $Exports<'react-voice-components/stories/VoiceRecognitionDemo'>;
}
declare module 'react-voice-components/webpackfile.js' {
  declare module.exports: $Exports<'react-voice-components/webpackfile'>;
}
