// flow-typed signature: 2f4f37b719e479b7a3aac3feab3c09c0
// flow-typed version: <<STUB>>/react-speech_v^0.3.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-speech'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-speech' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-speech/dist/react-speech' {
  declare module.exports: any;
}

declare module 'react-speech/dist/react-speech.min' {
  declare module.exports: any;
}

declare module 'react-speech/src/button' {
  declare module.exports: any;
}

declare module 'react-speech/src/speech' {
  declare module.exports: any;
}

declare module 'react-speech/src/speechSynthesis' {
  declare module.exports: any;
}

declare module 'react-speech/src/style' {
  declare module.exports: any;
}

declare module 'react-speech/test/button' {
  declare module.exports: any;
}

declare module 'react-speech/test/mockSpeechSynthesis' {
  declare module.exports: any;
}

declare module 'react-speech/test/setup' {
  declare module.exports: any;
}

declare module 'react-speech/test/speech' {
  declare module.exports: any;
}

declare module 'react-speech/test/speechSynthesis' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-speech/dist/react-speech.js' {
  declare module.exports: $Exports<'react-speech/dist/react-speech'>;
}
declare module 'react-speech/dist/react-speech.min.js' {
  declare module.exports: $Exports<'react-speech/dist/react-speech.min'>;
}
declare module 'react-speech/index' {
  declare module.exports: $Exports<'react-speech'>;
}
declare module 'react-speech/index.js' {
  declare module.exports: $Exports<'react-speech'>;
}
declare module 'react-speech/index' {
  declare module.exports: $Exports<'react-speech'>;
}
declare module 'react-speech/index.jsx' {
  declare module.exports: $Exports<'react-speech'>;
}
declare module 'react-speech/src/button.js' {
  declare module.exports: $Exports<'react-speech/src/button'>;
}
declare module 'react-speech/src/speech.js' {
  declare module.exports: $Exports<'react-speech/src/speech'>;
}
declare module 'react-speech/src/speechSynthesis.js' {
  declare module.exports: $Exports<'react-speech/src/speechSynthesis'>;
}
declare module 'react-speech/src/style.js' {
  declare module.exports: $Exports<'react-speech/src/style'>;
}
declare module 'react-speech/test/button.js' {
  declare module.exports: $Exports<'react-speech/test/button'>;
}
declare module 'react-speech/test/mockSpeechSynthesis.js' {
  declare module.exports: $Exports<'react-speech/test/mockSpeechSynthesis'>;
}
declare module 'react-speech/test/setup.js' {
  declare module.exports: $Exports<'react-speech/test/setup'>;
}
declare module 'react-speech/test/speech.js' {
  declare module.exports: $Exports<'react-speech/test/speech'>;
}
declare module 'react-speech/test/speechSynthesis.js' {
  declare module.exports: $Exports<'react-speech/test/speechSynthesis'>;
}
