// flow-typed signature: 1d182484b3961aa1c473352833654e12
// flow-typed version: <<STUB>>/react-dnd-test-backend_v^7.4.4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-test-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-test-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-test-backend/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'react-dnd-test-backend/lib/cjs/TestBackend' {
  declare module.exports: any;
}

declare module 'react-dnd-test-backend/lib/esm/index' {
  declare module.exports: any;
}

declare module 'react-dnd-test-backend/lib/esm/TestBackend' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-test-backend/lib/cjs/index.js' {
  declare module.exports: $Exports<'react-dnd-test-backend/lib/cjs/index'>;
}
declare module 'react-dnd-test-backend/lib/cjs/TestBackend.js' {
  declare module.exports: $Exports<'react-dnd-test-backend/lib/cjs/TestBackend'>;
}
declare module 'react-dnd-test-backend/lib/esm/index.js' {
  declare module.exports: $Exports<'react-dnd-test-backend/lib/esm/index'>;
}
declare module 'react-dnd-test-backend/lib/esm/TestBackend.js' {
  declare module.exports: $Exports<'react-dnd-test-backend/lib/esm/TestBackend'>;
}
