// flow-typed signature: f4ef597379865ed2f6ce5b68c0dc3c21
// flow-typed version: <<STUB>>/react-toggle-button_v^2.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toggle-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toggle-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toggle-button/demo/react-toggle-buttonDemo' {
  declare module.exports: any;
}

declare module 'react-toggle-button/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toggle-button/demo/react-toggle-buttonDemo.js' {
  declare module.exports: $Exports<'react-toggle-button/demo/react-toggle-buttonDemo'>;
}
declare module 'react-toggle-button/lib/index.js' {
  declare module.exports: $Exports<'react-toggle-button/lib/index'>;
}
