// flow-typed signature: 6557b1efbd6ee72986bafd59fac6d8de
// flow-typed version: <<STUB>>/react-style-tag_v^2.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-style-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-style-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-style-tag/dist/react-style-tag' {
  declare module.exports: any;
}

declare module 'react-style-tag/dist/react-style-tag.min' {
  declare module.exports: any;
}

declare module 'react-style-tag/es/blob' {
  declare module.exports: any;
}

declare module 'react-style-tag/es/constants' {
  declare module.exports: any;
}

declare module 'react-style-tag/es/hash' {
  declare module.exports: any;
}

declare module 'react-style-tag/es/index' {
  declare module.exports: any;
}

declare module 'react-style-tag/es/options' {
  declare module.exports: any;
}

declare module 'react-style-tag/es/Style' {
  declare module.exports: any;
}

declare module 'react-style-tag/es/styles' {
  declare module.exports: any;
}

declare module 'react-style-tag/lib/blob' {
  declare module.exports: any;
}

declare module 'react-style-tag/lib/constants' {
  declare module.exports: any;
}

declare module 'react-style-tag/lib/hash' {
  declare module.exports: any;
}

declare module 'react-style-tag/lib/index' {
  declare module.exports: any;
}

declare module 'react-style-tag/lib/options' {
  declare module.exports: any;
}

declare module 'react-style-tag/lib/Style' {
  declare module.exports: any;
}

declare module 'react-style-tag/lib/styles' {
  declare module.exports: any;
}

declare module 'react-style-tag/test/blob' {
  declare module.exports: any;
}

declare module 'react-style-tag/test/hash' {
  declare module.exports: any;
}

declare module 'react-style-tag/test/helpers/setup-browser-env' {
  declare module.exports: any;
}

declare module 'react-style-tag/test/options' {
  declare module.exports: any;
}

declare module 'react-style-tag/test/Style' {
  declare module.exports: any;
}

declare module 'react-style-tag/test/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-style-tag/dist/react-style-tag.js' {
  declare module.exports: $Exports<'react-style-tag/dist/react-style-tag'>;
}
declare module 'react-style-tag/dist/react-style-tag.min.js' {
  declare module.exports: $Exports<'react-style-tag/dist/react-style-tag.min'>;
}
declare module 'react-style-tag/es/blob.js' {
  declare module.exports: $Exports<'react-style-tag/es/blob'>;
}
declare module 'react-style-tag/es/constants.js' {
  declare module.exports: $Exports<'react-style-tag/es/constants'>;
}
declare module 'react-style-tag/es/hash.js' {
  declare module.exports: $Exports<'react-style-tag/es/hash'>;
}
declare module 'react-style-tag/es/index.js' {
  declare module.exports: $Exports<'react-style-tag/es/index'>;
}
declare module 'react-style-tag/es/options.js' {
  declare module.exports: $Exports<'react-style-tag/es/options'>;
}
declare module 'react-style-tag/es/Style.js' {
  declare module.exports: $Exports<'react-style-tag/es/Style'>;
}
declare module 'react-style-tag/es/styles.js' {
  declare module.exports: $Exports<'react-style-tag/es/styles'>;
}
declare module 'react-style-tag/lib/blob.js' {
  declare module.exports: $Exports<'react-style-tag/lib/blob'>;
}
declare module 'react-style-tag/lib/constants.js' {
  declare module.exports: $Exports<'react-style-tag/lib/constants'>;
}
declare module 'react-style-tag/lib/hash.js' {
  declare module.exports: $Exports<'react-style-tag/lib/hash'>;
}
declare module 'react-style-tag/lib/index.js' {
  declare module.exports: $Exports<'react-style-tag/lib/index'>;
}
declare module 'react-style-tag/lib/options.js' {
  declare module.exports: $Exports<'react-style-tag/lib/options'>;
}
declare module 'react-style-tag/lib/Style.js' {
  declare module.exports: $Exports<'react-style-tag/lib/Style'>;
}
declare module 'react-style-tag/lib/styles.js' {
  declare module.exports: $Exports<'react-style-tag/lib/styles'>;
}
declare module 'react-style-tag/test/blob.js' {
  declare module.exports: $Exports<'react-style-tag/test/blob'>;
}
declare module 'react-style-tag/test/hash.js' {
  declare module.exports: $Exports<'react-style-tag/test/hash'>;
}
declare module 'react-style-tag/test/helpers/setup-browser-env.js' {
  declare module.exports: $Exports<'react-style-tag/test/helpers/setup-browser-env'>;
}
declare module 'react-style-tag/test/options.js' {
  declare module.exports: $Exports<'react-style-tag/test/options'>;
}
declare module 'react-style-tag/test/Style.js' {
  declare module.exports: $Exports<'react-style-tag/test/Style'>;
}
declare module 'react-style-tag/test/styles.js' {
  declare module.exports: $Exports<'react-style-tag/test/styles'>;
}
