// flow-typed signature: 2db137916ccb0992fbc4f3a4d725817b
// flow-typed version: <<STUB>>/redux-flash_v^2.0.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-flash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-flash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-flash/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-flash/lib/flashMessageType' {
  declare module.exports: any;
}

declare module 'redux-flash/lib/index' {
  declare module.exports: any;
}

declare module 'redux-flash/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-flash/lib/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-flash/lib/actions.js' {
  declare module.exports: $Exports<'redux-flash/lib/actions'>;
}
declare module 'redux-flash/lib/flashMessageType.js' {
  declare module.exports: $Exports<'redux-flash/lib/flashMessageType'>;
}
declare module 'redux-flash/lib/index.js' {
  declare module.exports: $Exports<'redux-flash/lib/index'>;
}
declare module 'redux-flash/lib/middleware.js' {
  declare module.exports: $Exports<'redux-flash/lib/middleware'>;
}
declare module 'redux-flash/lib/reducer.js' {
  declare module.exports: $Exports<'redux-flash/lib/reducer'>;
}
