// flow-typed signature: be563e695756abf02383c489be6a28db
// flow-typed version: <<STUB>>/redux-persist-transform-filter_v^0.0.18/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-transform-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-transform-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-transform-filter/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-transform-filter/dist/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-filter/dist/index'>;
}
declare module 'redux-persist-transform-filter/index' {
  declare module.exports: $Exports<'redux-persist-transform-filter'>;
}
declare module 'redux-persist-transform-filter/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-filter'>;
}
