// flow-typed signature: 79553c9e2c7698cedf2e74a89e20e267
// flow-typed version: <<STUB>>/robotstxt-webpack-plugin_v^5.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'robotstxt-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'robotstxt-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'robotstxt-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'robotstxt-webpack-plugin/dist/RobotstxtPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'robotstxt-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'robotstxt-webpack-plugin/dist/cjs'>;
}
declare module 'robotstxt-webpack-plugin/dist/RobotstxtPlugin.js' {
  declare module.exports: $Exports<'robotstxt-webpack-plugin/dist/RobotstxtPlugin'>;
}
