// flow-typed signature: 3c8475d3593e00aa8c30b1ee16355e15
// flow-typed version: <<STUB>>/semantic-ui-less_v^2.4.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-ui-less'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-ui-less' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-ui-less/definitions/behaviors/api' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/behaviors/colorize' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/behaviors/form' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/behaviors/state' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/behaviors/visibility' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/behaviors/visit' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/globals/site' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/accordion' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/checkbox' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/dimmer' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/dropdown' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/embed' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/modal' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/nag' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/popup' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/progress' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/rating' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/search' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/shape' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/sidebar' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/sticky' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/tab' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/definitions/modules/transition' {
  declare module.exports: any;
}

declare module 'semantic-ui-less/package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-ui-less/definitions/behaviors/api.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/behaviors/api'>;
}
declare module 'semantic-ui-less/definitions/behaviors/colorize.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/behaviors/colorize'>;
}
declare module 'semantic-ui-less/definitions/behaviors/form.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/behaviors/form'>;
}
declare module 'semantic-ui-less/definitions/behaviors/state.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/behaviors/state'>;
}
declare module 'semantic-ui-less/definitions/behaviors/visibility.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/behaviors/visibility'>;
}
declare module 'semantic-ui-less/definitions/behaviors/visit.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/behaviors/visit'>;
}
declare module 'semantic-ui-less/definitions/globals/site.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/globals/site'>;
}
declare module 'semantic-ui-less/definitions/modules/accordion.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/accordion'>;
}
declare module 'semantic-ui-less/definitions/modules/checkbox.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/checkbox'>;
}
declare module 'semantic-ui-less/definitions/modules/dimmer.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/dimmer'>;
}
declare module 'semantic-ui-less/definitions/modules/dropdown.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/dropdown'>;
}
declare module 'semantic-ui-less/definitions/modules/embed.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/embed'>;
}
declare module 'semantic-ui-less/definitions/modules/modal.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/modal'>;
}
declare module 'semantic-ui-less/definitions/modules/nag.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/nag'>;
}
declare module 'semantic-ui-less/definitions/modules/popup.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/popup'>;
}
declare module 'semantic-ui-less/definitions/modules/progress.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/progress'>;
}
declare module 'semantic-ui-less/definitions/modules/rating.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/rating'>;
}
declare module 'semantic-ui-less/definitions/modules/search.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/search'>;
}
declare module 'semantic-ui-less/definitions/modules/shape.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/shape'>;
}
declare module 'semantic-ui-less/definitions/modules/sidebar.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/sidebar'>;
}
declare module 'semantic-ui-less/definitions/modules/sticky.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/sticky'>;
}
declare module 'semantic-ui-less/definitions/modules/tab.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/tab'>;
}
declare module 'semantic-ui-less/definitions/modules/transition.js' {
  declare module.exports: $Exports<'semantic-ui-less/definitions/modules/transition'>;
}
declare module 'semantic-ui-less/package.js' {
  declare module.exports: $Exports<'semantic-ui-less/package'>;
}
