// @flow

import * as m from './model';

export const dummyContentItemsById: m.ContentItemsById = {
  w4lg2u0p1h: {
    id: 'w4lg2u0p1h',
    type: m.contentItemTypes.ROOT,
    isEditing: false,
    childItemIds: ['qflasjgtxr'],
  },
  qflasjgtxr: {
    id: 'qflasjgtxr',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Lorem ipsum',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['plqfm799be', 'a8ntqiiho1'],
  },
  plqfm799be: ({
    id: 'plqfm799be',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Lorem **ipsum** dolor `sit` amet, [consectetur](https://www.lipsum.com) adipiscing *elit*.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  a8ntqiiho1: ({
    id: 'a8ntqiiho1',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Mauris accumsan pretium sem, in volutpat nibh sodales a. Nulla blandit posuere ex, et facilisis dui volutpat in. Fusce tincidunt sed ipsum quis varius. Quisque vitae laoreet sem.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  qyrgv0bcd6: {
    id: 'qyrgv0bcd6',
    type: m.contentItemTypes.ROOT,
    isEditing: false,
    childItemIds: ['ivks4jgtxr', 'j0vcu0y7vk', 'ua32xchh7q'],
  },
  j0vcu0y7vk: {
    id: 'j0vcu0y7vk',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Nam malesuada fermentum',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['yp8bumunth', 'u9niafk733'],
  },
  yp8bumunth: ({
    id: 'yp8bumunth',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Nullam ultrices rhoncus quam vulputate bibendum. Aliquam vehicula augue quis nibh iaculis semper.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['uieqlbgnxb'],
  }: m.ParagraphContentItem),
  uieqlbgnxb: ({
    id: 'uieqlbgnxb',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Morbi sed felis quis mi luctus malesuada at eu neque. Integer auctor lorem leo, ut semper massa dignissim et. Nulla dictum ullamcorper mattis. Suspendisse suscipit porttitor gravida. Aliquam porttitor tortor augue, sit amet lacinia ligula sodales sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed vitae purus sed odio pulvinar sagittis egestas non est. Aliquam nisi urna, faucibus in tellus in, tristique suscipit justo. Etiam rutrum nisl sit amet venenatis euismod. Nullam dictum imperdiet libero, et ornare est semper eu. Aenean dui ligula, vulputate et nisi eu, bibendum tempus arcu. In ornare sem et nunc volutpat, eu elementum neque vestibulum. Nullam dictum ipsum in viverra blandit. Suspendisse potenti.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  u9niafk733: ({
    id: 'u9niafk733',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'In sapien erat, venenatis iaculis volutpat in, pulvinar eu augue. Vestibulum porta euismod urna ac tempus. Praesent malesuada, ligula sed venenatis dictum, nulla ante finibus sem, nec suscipit felis lacus at urna. Vestibulum nec gravida sem. Pellentesque magna tortor, hendrerit ac nulla vitae, placerat gravida tortor.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['vrci6v35s7', 'cpi389s1e3'],
  }: m.ParagraphContentItem),
  vrci6v35s7: ({
    id: 'vrci6v35s7',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Sed hendrerit eget metus nec elementum. Aenean commodo semper sapien, nec porta leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla blandit elit et metus tincidunt semper. Sed ac tellus odio. Sed placerat faucibus leo a convallis. Pellentesque eget libero at lacus rutrum pretium.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  cpi389s1e3: ({
    id: 'cpi389s1e3',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Sed ut neque tristique, venenatis purus a, consequat orci. Aenean sed lectus et ante aliquet maximus. Integer hendrerit odio volutpat tincidunt consectetur. Cras venenatis, nibh a dignissim consectetur, augue tortor viverra nisi, quis euismod urna ligula ac turpis. Pellentesque eget faucibus urna, id sodales odio. Quisque ipsum ante, fringilla elementum mauris vel, tincidunt rhoncus augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  ua32xchh7q: {
    id: 'ua32xchh7q',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Phasellus posuere tincidunt enim',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['rnnvciso5i', 'bz807z2zha'],
  },
  rnnvciso5i: ({
    id: 'rnnvciso5i',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Etiam euismod sed erat vel tincidunt. Ut at dui non orci tincidunt ultricies. Sed aliquam ligula ultrices pretium laoreet.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  bz807z2zha: ({
    id: 'bz807z2zha',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Nullam pharetra malesuada nibh, nec gravida turpis pharetra nec. Donec nec semper dolor.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  ivks4jgtxr: {
    id: 'ivks4jgtxr',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'This is a heading',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['oswmjc09be', 'jbv2ju5jc6'],
  },
  oswmjc09be: ({
    id: 'oswmjc09be',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Lorem **ipsum** dolor `sit` amet, [consectetur](https://www.lipsum.com) adipiscing *elit*.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  jbv2ju5jc6: ({
    id: 'jbv2ju5jc6',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Mauris accumsan pretium sem, in volutpat nibh sodales a. Nulla blandit posuere ex, et facilisis dui volutpat in. Fusce tincidunt sed ipsum quis varius. Quisque vitae laoreet sem.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  kcosdhj38v: {
    id: 'kcosdhj38v',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Open Webslides slide rendering',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['vl4jfkdj4l', 'kdo4lbvn5l', 'lhjdki4hvi', 'dk3j5cl34k', 'dlidlf3ejk'],
  },
  kdo4lbvn5l: {
    id: 'kdo4lbvn5l',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Subheading 1',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['kdl3l4jkvd'],
  },
  kdl3l4jkvd: ({
    id: 'kdl3l4jkvd',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Lorem **ipsum** dolor `sit` amet, [consectetur](https://www.lipsum.com) adipiscing *elit*. Mauris *accumsan* pretium sem, in volutpat nibh sodales a. **Nulla blandit** posuere ex, et [facilisis](https://www.lipsum.com) dui volutpat in.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  vl4jfkdj4l: ({
    id: 'vl4jfkdj4l',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Introduction to the *Open Webslides **Slide Rendering** for noobs*',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  lhjdki4hvi: {
    id: 'lhjdki4hvi',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Subheading 2',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['kdloeijdj3'],
  },
  dk3j5cl34k: ({
    id: 'dk3j5cl34k',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Lorem **ipsum** dolor `sit` amet, [consectetur](https://www.lipsum.com) adipiscing *elit*.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  kdloeijdj3: ({
    id: 'kdloeijdj3',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Lorem **ipsum** dolor `sit` amet, [consectetur](https://www.lipsum.com) adipiscing *elit*. Mauris *accumsan* pretium sem, in volutpat nibh sodales a. **Nulla blandit** posuere ex, et [facilisis](https://www.lipsum.com) dui volutpat in.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  dlidlf3ejk: {
    id: 'dlidlf3ejk',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Subheading 3',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  },
  kchwki48cd: {
    id: 'kchwki48cd',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Yet Another Heading That Is Boring',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['kweoi4kivf'],
  },
  kweoi4kivf: {
    id: 'kweoi4kivf',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Yep, super boring here',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: ['focej3icjd'],
  },
  focej3icjd: ({
    id: 'focej3icjd',
    type: m.contentItemTypes.PARAGRAPH,
    isEditing: false,
    text: 'Lorem **ipsum** dolor `sit` amet, [consectetur](https://www.lipsum.com) adipiscing *elit*. Mauris *accumsan* pretium sem, in volutpat nibh sodales a. **Nulla blandit** posuere ex, et [facilisis](https://www.lipsum.com) dui volutpat in.',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  }: m.ParagraphContentItem),
  ck2k4kvcj4: {
    id: 'ck2k4kvcj4',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: '10 Reasons Why You Should Read This',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  },
  ldicl3j4jk: {
    id: 'ldicl3j4jk',
    type: m.contentItemTypes.HEADING,
    isEditing: false,
    text: 'Welcome to the presentation',
    metadata: {
      tags: [],
      visibilityOverrides: {},
    },
    subItemIds: [],
  },
};
