// @flow
/* eslint-disable import/no-duplicates */

import * as model from './model';

import {
  contentItemTypes,
  symbolContentItemTypes,
  plainTextContentItemTypes,
  mediaContentItemTypes,
  taggableContentItemTypes,
  subableContentItemTypes,
  containerContentItemTypes,
  highlightTypes,
  tagTypes,
  visibilityTypes,
} from './model';
import type {
  ContentItemType,
  SymbolContentItemType,
  PlainTextContentItemType,
  MediaContentItemType,
  TaggableContentItemType,
  SubableContentItemType,
  ContainerContentItemType,
  Metadata,
  BaseHighlight,
  MildEmphasisHighlight,
  StrongEmphasisHighlight,
  LinkHighlight,
  Highlight,
  Tag,
  Visibility,
  BaseContentItem,
  SymbolContentItem,
  PlainTextContentItem,
  MediaContentItem,
  TaggableContentItem,
  SubableContentItem,
  ContainerContentItem,
  RootContentItem,
  HeadingContentItem,
  ParagraphContentItem,
  ListContentItem,
  ListItemContentItem,
  BlockquoteContentItem,
  CodeContentItem,
  ImageContentItem,
  VideoContentItem,
  AudioContentItem,
  IframeContentItem,
  SlideBreakContentItem,
  CourseBreakContentItem,
  ContentItem,
  ContentItemsState,
} from './model';

const contentItems = {
  model,
};

export {
  contentItemTypes,
  symbolContentItemTypes,
  plainTextContentItemTypes,
  mediaContentItemTypes,
  taggableContentItemTypes,
  subableContentItemTypes,
  containerContentItemTypes,
  highlightTypes,
  tagTypes,
  visibilityTypes,
};
export type {
  ContentItemType,
  SymbolContentItemType,
  PlainTextContentItemType,
  MediaContentItemType,
  TaggableContentItemType,
  SubableContentItemType,
  ContainerContentItemType,
  Metadata,
  BaseHighlight,
  MildEmphasisHighlight,
  StrongEmphasisHighlight,
  LinkHighlight,
  Highlight,
  Tag,
  Visibility,
  BaseContentItem,
  SymbolContentItem,
  PlainTextContentItem,
  MediaContentItem,
  TaggableContentItem,
  SubableContentItem,
  ContainerContentItem,
  RootContentItem,
  HeadingContentItem,
  ParagraphContentItem,
  ListContentItem,
  ListItemContentItem,
  BlockquoteContentItem,
  CodeContentItem,
  ImageContentItem,
  VideoContentItem,
  AudioContentItem,
  IframeContentItem,
  SlideBreakContentItem,
  CourseBreakContentItem,
  ContentItem,
  ContentItemsState,
};
export default contentItems;
